[project]
name = "n-gram"
version = "0.1.0"
description = "Experimental results for optimizing n-gram models."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "huggingface-hub>=1.33.0",
    "loguru>=0.7.3",
    "matplotlib>=3.11.2",
    "numpy>=2.5.3",
    "pydivsufsort>=0.0.20",
    "tokenizers>=0.23.2",
    "tqdm>=4.70.1",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "ruff>=0.16.9",
]
